from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import BlogPost

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

import random

@login_required
def dashboard(request):
    posts = BlogPost.objects.filter(author=request.user)
    return render(request, 'blog/dashboard.html', {'posts': posts})

@login_required
def create_post(request):
    if request.method == 'POST':
        prompt = request.POST.get('prompt')
        
        # Mock AI Generation
        title = f"AI Thoughts on {prompt.title()}" if prompt else "Generated Title"
        content = (
            f"This is a mock AI-generated post about {prompt}. "
            "In a real scenario, this would be generated by calling an API like OpenAI or Gemini. "
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
            "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
            "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        )
        # Mock Unsplash Image
        keywords = prompt.split()[0] if prompt else "tech"
        random_id = random.randint(1, 1000)
        unsplash_image_url = f"https://picsum.photos/seed/{random_id}/800/400"
        
        post = BlogPost.objects.create(
            title=title,
            content=content,
            author=request.user,
            unsplash_image_url=unsplash_image_url,
            is_ai_generated=True
        )
        return redirect('post_detail', pk=post.pk)
        
    return render(request, 'blog/create_post.html')

@login_required
def post_detail(request, pk):
    post = BlogPost.objects.get(pk=pk, author=request.user)
    return render(request, 'blog/post_detail.html', {'post': post})

